#!/bin/bash
source /infra/utils

set -e
set -u
set -x

TARGET=${TARGET:-..}
cd $TARGET

GUESS=${PWD#*omero-cli-*}
PLUGIN=${PLUGIN:-$GUESS}

export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:/bin/java::")
export JAVA_LD_LIBRARY_PATH="$JAVA_HOME/lib/:$JAVA_HOME/lib/server"
export CONDA_BACKUP_JAVA_HOME=$JAVA_HOME
export CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=$JAVA_LD_LIBRARY_PATH

# installation of ArcCommander which is needed for ARC export option
wget --quiet https://github.com/nfdi4plants/arcCommander/releases/download/v0.5.0-linux.x64/arc
mkdir $HOME/bin
mv arc $HOME/bin/
chmod a+x $HOME/bin/arc
export PATH="$HOME/bin:$PATH"
arc --version

source /tmp/miniconda/bin/activate
conda init
conda activate omero

export OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server}
omero $PLUGIN -h
python setup.py test -t test -i ${OMERO_DIST}/etc/ice.config -vs