version: '3'

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
  omero:
    build:
      context: ./omeroserver
      args:
        - OMEROSERVER_BASE_IMAGE=openmicroscopy/omero-server:5
    environment:
      - ROOTPASS=omero
      - CONFIG_omero_db_user=postgres
      - CONFIG_omero_db_name=postgres
      - CONFIG_omero_db_pass=postgres
      - CONFIG_omero_upgrades_url=
      - CONFIG_Ice_IPv6=0
      - CONFIG_omero_policy_binary__access=+read,+write,+image,+plate
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    ports:
      - "4063:4063"
      - "4064:4064"
  web:
    build:
      context: ./omeroweb
      args:
        - OMEROWEB_BASE_IMAGE=openmicroscopy/omero-web-standalone:5
    environment:
      - CONFIG_omero_upgrades_url=
      - CONFIG_Ice_IPv6=0
    ports:
      - "4080:4080"
