name: OMERO
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: cli
    steps:
      - uses: actions/checkout@v3
      - name: Launch OMERO test database
        run: sudo chmod +x .omero/* && .omero/compose up -d
        env:
          ROOTPASS: omero
          POSTGRES_IMAGE: postgres
          POSTGRES_VERSION: 10
          POSTGRES_PASSWORD: postgres
          OMERO_SERVER_IMAGE: openmicroscopy/omero-server
          OMERO_SERVER_VERSION: 5
          OMERO_SERVER_TCP: "4063:"
          OMERO_SERVER_SSL: "4064:"
          OMERO_WEB_IMAGE: openmicroscopy/omero-web-standalone
          OMERO_WEB_VERSION: 5
          OMERO_WEB_PORT: "4080:"
          BUILD_IMAGE: adoptopenjdk:11-jdk-hotspot-bionic
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: "3.8"
      - name: Build omero_arc
        run: |
          $CONDA/bin/conda install -c anaconda python=3.8
          $CONDA/bin/conda install -c conda-forge zeroc-ice=3.6.5
          $CONDA/bin/python -m pip install "omero-cli-transfer @ git+https://github.com/ome/omero-cli-transfer@main"
          $CONDA/bin/python -m pip install .[dev]
      - name: Install omero_arc dependencies
        run: |
          wget --quiet https://github.com/nfdi4plants/arcCommander/releases/download/v0.5.0-linux.x64/arc
          mkdir $HOME/bin
          mv arc $HOME/bin/
          chmod a+x $HOME/bin/arc
          export PATH="$HOME/bin:$PATH"
          arc --version
      - name: Run tests
        run: |
          $CONDA/bin/conda install pytest
          export PATH="$CONDA/bin:$PATH"
          export PATH="$HOME/bin:$PATH"
          $CONDA/bin/pytest -v
        env:
          OMERODIR: .
          ICE_CONFIG: test/ice.config
      - name: Stop OMERO test database
        run: "sudo .omero/compose down"